CREATE TABLE WarrantyTypes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Name] VARCHAR(100) NOT NULL
);
INSERT INTO WarrantyTypes ([Name]) VALUES
('Assure'),
('Offline'),
('Citrus'),
('Distributor'),
('Easypos'),
('Ingram'),
('Warranty Pass'),
('Warranty Kit'),
('Zopper Secure'),
('Price Protection'),
('Home Assure'),
('New Warranty Kit'),
('Home Assure Commercial'),
('Custome Price'),
('Bucket Pricing'),
('Screen Protection'),
('Mobile EW'),
('Device Secure'),
('Zopper Cool Plus'),
('Device Secure Gold'),
('Zed Secure'),
('Vsuraksha'),
('Device Secure Subscription'),
('Accidental Damage Plan'),
('TV Damage'),
('Cashify'),
('On Demand Service'),
('Specs Assure'),
('ADLD'),
('EW + ADLD'),
('Mi Smart Upgrade'),
('Mi Screen Protect + Smart Upgrade'),
('Hospicash'),
('TWO WET SERVICE'),
('Extended Warranty (with service)'),
('Phone Secure Pro ( 2y  ADLD + 1y EW )'),
('EXTENDED WARRANTY (1 Y FESTIVE OFFER + EW)'),
('CYBER PROTECT'),
('COMPLETE CARE'),
('PAYTM NEW WARRANTY KIT'),
('PAYTM SCREEN PROTECTION'),
('XIAOMI CYBER PROTECT PLUS'),
('CROMA ZIPCARE AMC'),
('Service + EW'),
('INDIVIDUAL CYBER PROTECT'),
('COMPLETE CARE PLUS'),
('AC SUMMER PLAN');
