INSERT INTO Claims (
    TechnicianName, LmStatus, ItemName, Rating, L3ApprovalDate,
    ServicePartner, OtpRequired, DisplayName, Reasons, CallCloseRemarks,
    Concern, ClaimRegisteredPhoneNumber, ReasonOfLoss, EstimationFirst, SolvyPan,
    L2ServiceRejectionRemarks, ServicePartnerName, VoiceUrl, EstimationParts, CustomerAddress,
    BrandComplaintNumber, Address, OtpVerificationTimestamp, WarrantyStartDate, ChannelId,
    Phone, ItemPrice, WarrantyDuration, InvoiceDate, AssignedExecutiveName,
    AlternateContact, PlanSoldDate, RaiseAdditional, WarrantyTypeId, CustomerState,
    ItemSerialNumber, SolvyAddress, EndDate, ItemBrand, L2ServiceApprovalDate,
    ClaimVerificationDocumentUploadTimestamp, CustomerEmail, ChannelName, ClaimRedeemStatus, CreatedTime,
    EndStatus, L2InsuranceRejectionRemarks, CallAbortDateTime, ServicePartnerCity, EstimationDateTime,
    EstimationActionDate, RepairCompletionDate, WarrantyActivationCode, InvoiceActionDate, Status,
    ItemImei, HsnRequired, Pincode, EstimationLast, ServicePartnerPhone,
    ItemCategory, Technician, StartDate, CustomerAlternateEmail, ServicePartnerState,
    ClaimRedeemedDate, L2InsuranceApprovalDate, UtrNumber, ExtraInfo, AppointmentConfirmationTime,
    Created, ClaimRedeemed, PreviousVisitProductSerialNumber, ServicePartnerGST, CallAbortReason,
    InsuredCompany, SolvyGST, PaymentDone, ServicePartnerPincode, ClaimApproved,
    AppointmentPendingReason, Insured, StatusName, SelfInvoice, ServicePartnerPAN,
    ServicePartnerAddress, StoreName, L1ApprovalDate, PreviousStatus, FirstVisitTAT,
    PaymentStatus, EstimationPaymentAmount, CustomerPhone, Warranty, ClaimPaymentStatus,
    RegisteredBy, L1RejectionRemarks, DropDate, Cta, CustomerCity,
    Item, IsAddressEditable, RegisteredByName, L3RejectionRemarks, CreatedDate,
    ClaimType, RepairDoneTAT, WarrantyType, PickupDate, ItemCategoryId,
    PaymentId, Remarks, Type, ClaimAmount, Appointment,
    SolvyStateCode, PaymentTxnId, PaymentAmount, Amount, InvoiceNumber,
    CustomerName,SGST,CGST,IGST
) VALUES (
    NULL, NULL, 'DEVICE SECURE - GOLD', NULL, NULL,
    537416, 0, 'DEVICE SECURE GOLD', NULL, NULL,
    'Wet service Jet Pump required', NULL, NULL, NULL, 'AAPCS1780F',
    NULL, 'KAB ELECTRO SOLUTIONS', NULL, NULL, 'radha krishn pura gali no : 4 shikar shikar Rajasthan 332001',
    NULL, 400821, NULL, '2025-03-27', 13,
    NULL, 0, 12, NULL, NULL,
    NULL, '2025-03-27', 0, 21, 'Rajasthan',
    NULL, NULL, NULL, 'Daikin', NULL,
    NULL, '202503271907494504360188@croma.com', 'Croma', NULL, '16:04:56',
    NULL, NULL, NULL, 'Mathura', NULL,
    NULL, NULL, 'UNK5355169', NULL, 3,
    NULL, 0, 332001, NULL, '8433112032',
    'Air Conditioner', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    '2025-07-18T16:04:56.296', 0, NULL, '09IXPPS3444Q1Z6', NULL,
    NULL, '09AAPCS1780F1Z0', 'Not applicable', 281001, 0,
    NULL, 'NOT_INSURED', 'Service Centre Assigned', NULL, 'IXPPS3444Q',
    'B21 100ft road lajpat nagar near bajrang dharam kanta maholi road mathura 281001', 'Croma Device Secure', NULL, 3, NULL,
    NULL, NULL, '9700063639', 14512318, NULL,
    73201, NULL, NULL, NULL, 'Sikar',
    1463819, 0, 'Croma claim', NULL, '2025-07-18',
    3, NULL, 'DEVICE SECURE GOLD', NULL, 48,
    NULL, '.', NULL, NULL, 1752834896218,
    '09', NULL, NULL, NULL, NULL,
    'PARAM TRADERS','[]','[]','[]'
);
