CREATE TABLE Plans (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CatId INT NOT NULL,
    PlanName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255) NULL,
    Remark NVARCHAR(255) NULL,
    IsDisable BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_Plan_Categories FOREIGN KEY (CatId) REFERENCES Categories(id)
);
  ALTER TABLE plans
ADD BrandId INT NOT NULL DEFAULT 0;

ALTER TABLE Plans
ADD CONSTRAINT UQ_Plans_Cat_Brand_PlanName
UNIQUE (CatId, BrandId, PlanName);


 INSERT INTO Plans (CatId, PlanName, Description, Remark, IsDisable)
 VALUES
   (1, 'DEVICE SECURE - GOLD', 'DEVICE SECURE - GOLD', 'DEVICE SECURE - GOLD', 1),
   (2, 'DEVICE SECURE - GOLD 1', 'DEVICE SECURE - GOLD 1', 'DEVICE SECURE - GOLD 1', 1),
   (3, 'DEVICE SECURE - GOLD 2', 'DEVICE SECURE - GOLD 2', 'DEVICE SECURE - GOLD 2', 1);